# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EFA.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
import numpy as np
import pandas as pd

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QImage, QPixmap, QPainterPath, QPainter,QPen,QColor
from PyQt5.QtCore import Qt
import sys
# import openpyxl


sys.path.append('/functions')
from functions.fourier_approx_norm_modify import fourier_approx_norm_modify
from functions.calc_dc_components_modify import calc_dc_components_modify
from functions.code2axis import code2axis

